Table products {
	id integer [ pk, increment, not null, unique ]
	name varchar [ not null ]
	description varchar
	price real [ not null ]
}

Table inventory {
	id integer [ pk, increment, not null, unique ]
	quantity integer [ not null ]
	product_id integer [ not null ]
	uom varchar [ not null ]
	movement_type varchar [ not null, default: 'in', note: 'in, out' ]
	created_at datetime [ not null ]
	updated_at datetime [ not null ]
	reason varchar
}

Table orders {
	id integer [ pk, increment, not null, unique ]
	created_at datetime [ not null ]
	customer_id integer [ not null ]
	status varchar [ not null, default: 'placed', note: 'placed, cancelled, processing, shipped' ]
	notes text
}

Table order_items {
	id integer [ pk, increment, not null, unique ]
	quantity integer [ not null ]
	price real [ not null ]
	uom varchar
	order_id integer [ not null ]
}

Table customers {
	id integer [ pk, increment, not null, unique ]
	firstname varchar [ not null ]
	lastname varchar [ not null ]
	email varchar
	phone varchar [ not null ]
	address text [ not null ]
}

Table order_item_reservations {
	id integer [ pk, increment, not null, unique ]
	inventory_id integer [ not null ]
	order_item_id integer [ not null ]
}

Ref fk_products_id_inventory {
	products.id < inventory.product_id [ delete: restrict, update: no action ]
}

Ref fk_customers_id_orders {
	customers.id - orders.customer_id [ delete: no action, update: no action ]
}

Ref fk_orders_id_order_items {
	orders.id < order_items.order_id [ delete: cascade, update: no action ]
}

Ref fk_inventory_id_order_reservations {
	inventory.id - order_item_reservations.inventory_id [ delete: no action, update: no action ]
}

Ref fk_order_items_id_order_reservations {
	order_items.id - order_item_reservations.order_item_id [ delete: no action, update: no action ]
}