Table products {
	id integer [ pk, increment, not null, unique ]
	name varchar(255) [ not null ]
	description varchar(255)
	price real [ not null ]
	product_category_id integer [ not null ]
	featured_image text(65535) [ not null ]
	is_featured boolean [ not null, default: 0 ]
	socialmedia_image text(65535) [ not null ]
	disabled boolean [ not null, default: 0 ]
}

Table ProductCategory {
	id integer [ pk, increment, not null, unique ]
	name varchar(255) [ not null ]
	description 
}

Table inventory {
	id integer [ pk, increment, not null, unique ]
	quantity integer [ not null ]
	product_id integer [ not null ]
	uom varchar(10) [ not null ]
	movement_type varchar(255) [ not null, default: 'in' ]
	created_at datetime [ not null ]
	updated_at datetime [ not null ]
	reason varchar(255)
}

Table orders {
	id integer [ pk, increment, not null, unique ]
	created_at datetime [ not null ]
	customer_id integer [ not null ]
	status varchar(100) [ not null, default: 'placed' ]
	notes text(65535)
}

Table order_items {
	id integer [ pk, increment, not null, unique ]
	product_id integer [ not null ]
	quantity integer [ not null ]
	price real [ not null ]
	net_price real [ not null ]
	uom varchar(255) [ not null ]
	order_id integer [ not null ]
}

Table customers {
	id integer [ pk, increment, not null, unique ]
	firstname varchar(255) [ not null ]
	lastname varchar(255) [ not null ]
	email varchar(255)
	phone varchar(255) [ not null ]
	address text(65535) [ not null ]
}

Ref fk_inventory_product_id_products {
	inventory.product_id < products.id [ delete: restrict, update: no action ]
}

Ref fk_orders_customer_id_customers {
	orders.customer_id - customers.id [ delete: no action, update: no action ]
}

Ref fk_order_items_order_id_orders {
	order_items.order_id < orders.id [ delete: cascade, update: no action ]
}

Ref fk_products_product_category_id_ProductCategory {
	products.product_category_id < ProductCategory.id [ delete: no action, update: no action ]
}

Ref fk_order_items_product_id_products {
	order_items.product_id - products.id [ delete: no action, update: no action ]
}