services:
    juanpasabuyph:
        privileged: true
        build:
            context: .
            dockerfile: Dockerfile
        # limit memory
        deploy:
            resources:
                limits:
                    memory: 256M
        # use by curl
        hostname: juanpasabuyph.loc
        container_name: juanpasabuyph_app
        networks:
            - juan_network
        volumes:
            - ../..:/workspaces:cached
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        ports:
            - "8000:8000"
            - "5173:5173"
            - "9000:9000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jquanpasabuyph.rule=Host(`juanpasabuyph.loc`)"
            - "traefik.http.routers.juanpasabuyph.entrypoints=web"
            - "traefik.http.routers.juanpasabuyph.service=juanpasabuyph"
            - "traefik.http.services.juanpasabuyph.loadbalancer.server.port=8000"

networks:
    juan_network:
        external: true
        name: donz_network
