services:
    app:
        build:
            context: ../
            dockerfile: docker_ci/Dockerfile
        volumes:
            #- ${DOKPLOY_HOST_APP_PATH:-../}:/var/www/html
            - db:/var/www/html/database/database
            - storage:/var/www/html/storage
        expose:
            - "8080"
            - "8443"
        networks:
            - dokploy-network
        #environment:
            #AUTORUN_ENABLED: "true"
            #PHP_OPCACHE_ENABLE: "1"
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.timetracker.rule=Host(`timetracker.loc`)"
        - "traefik.http.routers.timetracker.entrypoints=web"
        - "traefik.http.services.timetracker.loadbalancer.server.port=8080"


networks:
  dokploy-network:
    name: dokploy-network
    external: true

volumes:
  db:
  storage:








